############# English navigation ##############

# main menu
[[main]]
name = "Главная"
pageRef = "/"
weight = 1

[[main]]
name = "Сведения об образовательной организации"
pageRef = "/education"
weight = 2

[[main]]
name = "Страницы"
weight = 3

[[main]]
parent = "Страницы"
name = "Программа обучения"
pageRef = "/programma"


# footer menu
[[footer]]
name = "Политика конфиденциальности"
pageRef = "/privacy-policy"
weight = 1
