############# English navigation ##############

# main menu
[[main]]
name = "Главная"
pageRef = "/"
weight = 1

[[main]]
name = "Сведения об образовательной организации"
pageRef = "/education"
weight = 2


# footer menu
[[footer]]
name = "Политика конфиденциальности"
pageRef = "/privacy-policy"
weight = 1
